### ISSUE TITLE
bug: cairo_filesystem detect_corelib fails when used as a git dependency

### ISSUE THREAD

**Issue by shramee** [starkware-libs/cairo#1595]
# Bug Report

**Cairo version:**

74b4d128ccb199045abde158ee247e5a351f3cae

**Current behavior:**

thread 'main' panicked at 'Corelib not found.', /Users/shramee/.cargo/git/checkouts/cairo-f086c7e6d4098a68/74b4d12/crates/cairo-filesystem/src/detect.rs:34:5

When using `cairo_compiler::db::RootDatabase;` to get default `let mut db_val = RootDatabase::default();`

Using crates from the git repo like so,

```toml
# . . .
[dependencies]

# Members of starkware-libs/cairo
# . . .
cairo-filesystem = { git = "https://github.com/starkware-libs/cairo" }
cairo-compiler = { git = "https://github.com/starkware-libs/cairo" }
# . . .
```

**Expected behavior:**

Corelib dir to be found from installed git crate path.

**Steps to reproduce:**

**Related code:**

Tiniest reproducible version:

Issue is in `cairo_filesystem::detect::detect_corelib`.

#### Cargo.toml
```toml
[package]
name = "cairo-corelibs-bug"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-filesystem = { git = "https://github.com/starkware-libs/cairo" }

[[bin]]
name = "test"
path = "test.rs"
```

#### test.rs
```rs
use cairo_filesystem::detect::detect_corelib;
fn main() {
    let path = detect_corelib();
    print!("Found corelibs at {:#?}.", path);
}
```

**Other information:**
