### ISSUE TITLE
bug: Can't use cairo-lang-starknet version 2.4.0 as a dependency of a rust project

### ISSUE THREAD

**Issue by marioiordanov** [starkware-libs/cairo#4956]
**Steps to reproduce:**

Create a new rust project, it doesn't matter if its a lib or bin.
Add cairo-lang-starknet = "=2.4.0" as a dependency to it.
It doesnt build. Because the version for each inner dependency of cairo-lang-starknet is:
```toml
cairo-lang-casm = { path = "../cairo-lang-casm", version = "2.4.0-rc6" }
cairo-lang-compiler = { path = "../cairo-lang-compiler", version = "2.4.0-rc6" }
cairo-lang-defs = { path = "../cairo-lang-defs", version = "2.4.0-rc6" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "2.4.0-rc6" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.4.0-rc6" }
cairo-lang-lowering = { path = "../cairo-lang-lowering", version = "2.4.0-rc6" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "2.4.0-rc6" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.4.0-rc6" }
cairo-lang-sierra-generator = { path = "../cairo-lang-sierra-generator", version = "2.4.0-rc6" }
cairo-lang-sierra-to-casm = { path = "../cairo-lang-sierra-to-casm", version = "2.4.0-rc6" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "2.4.0-rc6" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.0-rc6" }
```

Which means that if there are new version of all of the dependencies then cargo will download the new version, and in the case of today - it downloads the version 2.5.1 which has some breaking changes.
